RedHatInsights/xjoin-search

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/index.ts, src/schema/schema.graphql
On HBI we switched over to querying for fqdn in lowecase prematurely, we are getting lots of 400 errors from xjoin-search because of this. This PR will fix that by switching fqdn to using all lowercase operations.
refer the the PR that introduced the bug here for the reasoning behind the change: https://github.com/RedHatInsights/insights-host-inventory/pull/956
=> made fqdn use lowercase operations

src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/hosts.integration.ts, src/resolvers/hosts/index.ts, test/hosts.json
This PR addresses a bug introduced in #123, which would cause the query to fail if any of the operating_system fields were null. I also added some test hosts with different combinations of missing operating_system fields to verify that the update worked (thus the updated snapshots).
=> Fix operating_system ordering script

src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/index.ts, test/hosts.json
The current sorting script compares the whole OS as a single string, meaning "RHEL 8.2" > "RHEL 8.10". To combat this, this PR updates the sorting script to separately format the major and minor versions, prepending with the character `0` enough times to make each a 10-digit representation.
So with this change, the above example would actually result in the comparison "RHEL 0000000008.0000000002" < "RHEL 0000000008.0000000010", which is what we want.
=> OS version ordering fix

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/hosts.integration.ts, src/resolvers/inputInt.ts, src/schema/schema.graphql
In addition to filtering fields like operating_system using a range, we also need to be able to filter using exact matches. So, this PR adds an optional "eq" operation to the FilterInt type and modifies the resolver to work with either.
Also, I closed a parenthetical that was left open because it was bugging me.
=> Allow filtering of operating_system field (and other filterInts) using "eq"

scripts/update_from_schema.ts
Now the template in the ephemeral xjoin-search configmap will include all aspects of the pipeline and only update the mapping portion from the script.
=> Patch ephemeral mapping updater

scripts/update_from_schema.ts
Updated the ephemeral mapping updater to only modify system_profile_facts. The removal of the lowercase modifier was a byproduct of this. Now when the script is run, existing configuration outside of `system_profile_facts` remains the same.
=> Fix ephemeral update

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/hosts.integration.ts, src/resolvers/index.ts, src/schema/schema.graphql, test/helpers.ts, test/hosts.json
Addresses [ESSNTL-2445](https://issues.redhat.com/browse/ESSNTL-2445). Adds per-reporter staleness to the Host schema.
Will need [this xjoin-operator PR](https://github.com/RedHatInsights/xjoin-operator/pull/7) to be merged in order to actually return data.
=> Add per-reporter staleness to schema

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/hosts.integration.ts, src/resolvers/hosts/index.ts, src/resolvers/index.ts, src/resolvers/inputPerReporterStaleness.ts, src/schema/schema.graphql, test/helpers.ts, test/hosts.json, test/mapping.json
This is a continuation of PR #85. Adds support for a new flter on per_report_staleness data.
```
filter: {
per_reporter_staleness: {
reporter: "yupana"
stale_timestamp: {gte: "2020-02-10T08:07:03.354307Z"}
last_check_in: {gte: "2020-02-09T08:07:03.354307Z"}
check_in_succeeded: {is: true}
}
}
```
It also changes the mapping to index this data in elastic search correctly, and adds a way to query the new data:
```
data {
id
account
display_name
per_reporter_staleness {
reporter
stale_timestamp
last_check_in
check_in_succeeded
}
}
```
There are also tests to make sure that the filters work correctly.
=> Add per_reporter_staleness filter

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/hosts.integration.ts, src/resolvers/hosts/index.ts, src/resolvers/index.ts, src/resolvers/inputPerReporterStaleness.ts, src/schema/schema.graphql, test/helpers.ts, test/hosts.json, test/mapping.json
This is a follow-up on #150. Instead of changing the `per_reporter_staleness` field to a custom type, it uses a list of JSONObject, which is the structure we expect.
Now, since the query doesn't have to change, this should be able to be merged in without breaking HBI API.
=> Add per_reporter_staleness filter (take 2)

docs/schema.md, src/generated/graphql.ts, src/resolvers/hosts/__snapshots__/hosts.integration.ts.snap, src/resolvers/hosts/hosts.integration.ts, src/resolvers/hosts/index.ts, src/resolvers/index.ts, src/resolvers/inputPerReporterStaleness.ts, src/schema/schema.graphql, test/helpers.ts, test/hosts.json, test/mapping.json
This follows up on #151. It adds `per_reporter_staleness` and `per_reporter_staleness_flat` to the schema, and filters on `per_reporter_staleness_flat` specifically. The intent is to get the regular object data in the response, while filtering on the flattened version like this:
```
filter: {
per_reporter_staleness: {
reporter: "yupana"
stale_timestamp: {gte: "2020-02-10T08:07:03.354307Z"}
last_check_in: {gte: "2020-02-09T08:07:03.354307Z"}
check_in_succeeded: {is: true}
}
}
```
=> Support for flattened per-reporter staleness and its filters

build/checkimage.yaml
This github action is being added to get the latest base image for security compliance.
=> Add github action for updating xjoin-search's base image

build/Dockerfile
This PR implements [RHCLOUD-23978](https://issues.redhat.com/browse/RHCLOUD-23978), which is a sub-task of [RHCLOUD-23856](https://issues.redhat.com/browse/RHCLOUD-23856)
=> RHCLOUD-23978 update xjoin-search image to use ubi8-minimal

.github/workflows/update_from_schema.yaml
To be able to update `xjoin-search` to support the latest `inventory-schemas`, we need to get an Elasticsearch container running.
This patch adds the usage of `isbang/compose-action` to run the command `docker-compose up elasticsearch`.
Example of run: https://github.com/RedHatInsights/xjoin-search/actions/runs/4702162573/jobs/8339098926
=> Run elasticsearch container before updating schema

.github/CODEOWNERS
Adds the HBI committers team to the CODEOWNERS file so that we get added as reviewers to new PRs.
=> Add HBI committers to CODEOWNERS

src/generated/graphql.ts, src/schema/schema.graphql
Adds filters for the booted, cachedUpdate, rollback, and staged fields on the bootc_status object.
This supports [RHINENG-7729](https://issues.redhat.com/browse/RHINENG-7729). Ideally, we'd alter the code in the `update_from_schema.ts` script to work for multi-level objects like this, but the logic would need to become even more complex, and we only need to support it in the short-term.
After this PR is merged, the "update mapping" GH Action should work again.
=> fix(RHINENG-7729): Add filters to support bootc_status

src/generated/graphql.ts, src/schema/schema.graphql
Reverts RedHatInsights/xjoin-search#251
#251 was a hacky workaround to make some new filters work, but it didn't even fully work, so I'm reverting it.
=> Revert "fix(RHINENG-7729): Add filters to support bootc_status"

src/middleware/identity/impl.ts
This PR is related to [RHINENG-5479](https://issues.redhat.com/browse/RHINENG-5479).
It adds the identity type ServiceAccount to the allowed types.
More context on why this is necessary on the comments of the Jira task.
=> fix(RHINENG-5479): add identity type ServiceAccount

deploy/clowdapp.yaml, deploy/ephemeral.yaml
Removes the xjoin-api-gateway dependency from the clowdapp. xjoin-api-gateway was something made for v2; now that we are moving in a different direction, we need to remove this. Also, our builds are currently broken because we removed apicurio, which is needed for api-gateway.
=> Remove xjoin-api-gateway dependency

build_deploy.sh
It has been observed that the `build_deploy` script is set up so that when the SC build Job runs, it write a new image over the original `image_tag` on which the commit is based. 
This update fixes that issue.
=> fix(build_catalog): only create sc tag when building sc branch

security-scan.sh
This script will provide the same level of support as the standard PlatSec GitHub Workflow, but will run on a RHEL-Based Jenkins Node.
A copy of the [security-scan-source-template.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan-source-template.sh) has been added to this repo, and the (GitHub) `platsec-gh-vulnerability-scan` Jenkins Job has be added to the xjoin-search `build.yml` in App-Interface.
Similar to the standard GitHub Workflow, we can accommodate feature requests and provide updates on the fly and with full transparency. The `security-scan-source-template.sh` script, which sources the main [security-scan.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan.sh) script, allows us …
=> Adding Jenkins Security Scan Script
